module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        abyss: "#02060f",
        deep: "#04111f",
        surface: "#082236",
        elevated: "#0d3050",
        overlay: "#1a4a6e",
        "fg-primary": "#e8f4f8",
        "fg-secondary": "#9fb8c7",
        "fg-muted": "#5a7888",
        "fg-faint": "#3d5666",
        "glow-cyan": "#00f0d4",
        "glow-green": "#00ff88",
        "glow-yellow": "#ffcc00",
        "glow-orange": "#ff8800",
        "glow-red": "#ff3355",
        "glow-magenta": "#ff00aa",
        "viz-chl": "#00d4aa",
        "viz-temp": "#ff6b35",
        "viz-do": "#4ecdc4",
        "viz-turb": "#ffd23f",
        "viz-citizen": "#c77dff",
      },
      fontFamily: {
        display: ['"Bebas Neue"', '"Instrument Sans"', "Manrope", "system-ui", "sans-serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', '"Fira Code"', "monospace"],
        serif: ["Newsreader", "Georgia", "serif"],
      },
      boxShadow: {
        "glow-sm": "0 0 12px rgba(0, 240, 212, 0.25)",
        "glow-md": "0 0 24px rgba(0, 240, 212, 0.4)",
        "glow-lg": "0 0 48px rgba(0, 240, 212, 0.55)",
        "glow-red": "0 0 24px rgba(255, 51, 85, 0.5)",
      },
      maxWidth: {
        content: "1280px",
      },
      zIndex: {
        base: "0",
        card: "10",
        sticky: "20",
        drawer: "30",
        modal: "40",
        toast: "50",
        tooltip: "60",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { opacity: "0.55" },
          "50%": { opacity: "1" },
        },
        drift: {
          "0%": { transform: "translate3d(0,0,0)" },
          "50%": { transform: "translate3d(12px,-18px,0)" },
          "100%": { transform: "translate3d(0,0,0)" },
        },
        caustic: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "pulse-glow": "pulseGlow 2.4s ease-in-out infinite",
        drift: "drift 14s ease-in-out infinite",
        caustic: "caustic 18s ease infinite",
        shimmer: "shimmer 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
